name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.6
  provider: ^6.1.1
  location: ^5.0.3
  lottie: ^3.0.0
  cupertino_icons: ^1.0.8
  intl: 0.19.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    # Arka plan görselleri
    - assets/images/clear.jpg
    - assets/images/clouds.jpg
    - assets/images/rain.jpg
    - assets/images/thunderstorm.jpeg
    - assets/images/snow.jpg
    - assets/images/fog.jpg

    # Lottie animasyonları
    - assets/animations/clear.json
    - assets/animations/clouds.json
    - assets/animations/rain.json
    - assets/animations/thunderstorm.json
    - assets/animations/snow.json
    - assets/animations/fog.json
